<Project Sdk="Godot.NET.Sdk/4.7.2">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <EnableDynamicLoading>true</EnableDynamicLoading>
        <IsPackable>false</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.10.1" />
        <PackageReference Include="gdUnit4.api" Version="5.1.0-rc5" />
        <PackageReference Include="gdUnit4.test.adapter" Version="3.1.1" />
    </ItemGroup>

    <PropertyGroup>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
        <VSTestTestAdapterPath>none</VSTestTestAdapterPath>
        <TestFramework>GdUnit4</TestFramework>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="../src/Godex.Async.csproj" />
    </ItemGroup>

</Project>